/** Brand names for autocomplete (language-neutral where possible). */
export const COSMETIC_BRAND_SUGGESTIONS: string[] = [
  "MAC",
  "Maybelline",
  "L'Oréal Paris",
  "Dior",
  "Chanel",
  "Estée Lauder",
  "Fenty Beauty",
  "Rare Beauty",
  "Morphe",
  "Anastasia Beverly Hills",
  "Charlotte Tilbury",
  "NARS",
  "Too Faced",
  "Shiseido",
  "Innisfree",
  "Etude House",
  "3CE",
  "Merzy",
  "Black Rouge",
  "Peripera",
  "Romand",
];
